server:
  port: 8090

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml

spring:
  application:
    name: comment

  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comment?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    maxActive: 30
    minIdle: 5
    maxWait: 10000
    validationQuery: SELECT 'x'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

  redis:
    host: 127.0.0.1
    port: 6379

  zipkin:
    base-url: http://localhost:9411
  sleuth:
     sampler:
        rate: 1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8666/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    #配置以ip:port可访问到的地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

logbook:
  write:
    level: info
  format:
    style: http

file:
  path: /home/house/data/images
  prefix: http://127.0.0.1:8081/images
user:
  service:
    name: user
house:
  service:
    name: house
comment:
  service:
    name: comment

